services:
  edc:
    container_name: edc
    build:
      context: ./connector
    environment:
      - MY_EDC_NAME
      - MY_PARTICIPANT_ID
      - MY_EDC_FQDN
      - MY_EDC_PROTOCOL
      - EDC_KEYSTORE_PASSWORD
      - EDC_API_AUTH_KEY
      - EDC_OAUTH_CLIENT_ID
      - EDC_OAUTH_PROVIDER_JWKS_URL
      - EDC_OAUTH_TOKEN_URL
    ports:
      - 11001:11001
      - 11002:11002
      - 11003:11003
      - 11004:11004
      - 11005:11005
      - 11006:11006
    user: ${CONNECTOR_UID}:${CONNECTOR_GID}
    volumes:
      - ./vault:/vault
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db

  backend:
    container_name: backend
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./backend/nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ./backend/assets:/assets

  db:
    container_name: postgresql
    image: postgres:16
    env_file:
      - ./connector/.env_postgresql
    expose:
      - 5432
    user: ${POSTGRES_UID}:${POSTGRES_GID}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./db/home:/home/${LOGNAME}
      - /etc/passwd:/etc/passwd:ro

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
      URLS: '[ { url: "http://localhost:11000/openapi/management.yaml", name: "Management API" }, { url: "http://localhost:11000/openapi/catalog.yaml", name: "Catalog API" } ]'
    ports:
      - 11000:8080
    volumes:
      - ./openapi/yaml:/usr/share/nginx/html/openapi

  edc-another:
    container_name: edc-another
    build:
      context: ./connector
    env_file:
      - ./.env_another
    ports:
      - 21001:11001
      - 21002:11002
      - 21003:11003
      - 21004:11004
      - 21005:11005
    user: ${CONNECTOR_UID}:${CONNECTOR_GID}
    volumes:
      - ./demo:/vault
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db-another
    profiles: ["demo"]

  db-another:
    container_name: postgresql-another
    image: postgres:16
    env_file:
      - ./connector/.env_postgresql
    expose:
      - 5432
    user: ${POSTGRES_UID}:${POSTGRES_GID}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./demo/data:/var/lib/postgresql/data
      - ./demo/home:/home/${LOGNAME}
      - /etc/passwd:/etc/passwd:ro
    profiles: ["demo"]
